name: os_type
description: "A new Flutter plugin project."
version: 0.0.1
repository: https://github.com/qinshah/os_type

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ohos:
        pluginClass: OsTypePlugin
