name: os_type
description: "Useful for OS and web environment detection, supports HarmonyOS."
version: 0.1.0
repository: https://github.com/qinshah/os_type

environment:
  sdk: "^3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        dartPluginClass: OS
      ios:
        dartPluginClass: OS
      linux:
        dartPluginClass: OS
      windows:
        dartPluginClass: OS
      macos:
        dartPluginClass: OS
      web:
        dartPluginClass: OS
      ohos:
        pluginClass: OsTypePlugin
